name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@sschne'
      - name: Time in container
        run: echo "The time was ${{ steps.hello-world-action.outputs.time }}
