name: Docker action

on:
  push:
    branches:
      - main
    paths:
      - hello-world-docker-action/**
  workflow_dispatch:

jobs:
  container-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'sschne'
      - name: Time in container
        run: echo "The time was ${{ steps.hello-world-action.outputs.time }}
