name: Github Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by: ${{ github.event_name }}"
          echo "The branch name is ${{ github.ref }} and your repo is ${{ github.repository }}"
      - uses: actions/checkout@v4.1.1
      - name: List files in the repository
        run: |
          echo "repository contains following files"
          find .
