name: Github Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by: ${{ github.event_name }}"
          echo "The branch name is ${{ github.ref }} and your repo is ${{ github.repository }}"
      - uses: actions/checkout@v4.1.1
      - name: List files in the repository
        run: |
          echo "repository contains following files"
          find .
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: Test
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: Load-Test
    environment: Production
    if: github.inputs.environment == "Production"
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "Step 2 deploying..."
          sleep 10
      - run: |
          echo "Step 3 deploying..."
          sleep 10
      - run: |
          echo "Step 4 deploying..."
          sleep 10
      - run: |
          echo "Step 5 deploying..."
          sleep 10
  
